{% set name = "kokkos-kernels" %}
{% set version = "4.6.02" %}
{% set so_version = "4.6.02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kokkos/kokkos-kernels/releases/download/{{ version }}/kokkos-kernels-{{ version }}.tar.gz
  sha256: a953f445660ed5aaab10e18fc4a90c4c178291e9d9d97d20abd4e6027f1193ec

build:
  skip: true  # [win]
  number: 0
  run_exports:
    - {{ pin_subpackage('kokkos-kernels') }}

requirements:
  build:
    - cmake >=3.21.1,<4
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - ninja
  host:
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - kokkos >=4.0.0,<5
  run:
    - kokkos >=4.0.0,<5
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

test:
  source_files:
    - example/batched_solve
  commands:
    - $CXX example/batched_solve/team_GMRES.cpp -o team_GMRES -std=c++17 -I$PREFIX/include -L$PREFIX/lib -lkokkoscontainers -lkokkoscore -lkokkoskernels -fopenmp
  # Lots more CMake files; just checking for one
    - test -f $PREFIX/lib/cmake/KokkosKernels/KokkosKernelsConfig.cmake  # [unix]
  # Testing explicitly for all shared libs, but not links
    - test -f $PREFIX/lib/libkokkoskernels.so  # [linux]
    - test -f $PREFIX/lib/libkokkoskernels.dylib  # [osx]
  # There are lots more headers; only test for one.
    - test -f $PREFIX/include/KokkosKernels_Handle.hpp  # [unix]
  requires:
    - {{ compiler('cxx') }}

about:
  home: https://kokkos.org/
  summary: >
    Kokkos Kernels is a software library of linear algebra and graph algorithms used across many HPC applications to
    achieve best (not just good) performance on every architecture.
  description: >
    The baseline version of this library is written using
    the Kokkos Core programming model for portability and good performance. The library has architecture-specific
    optimizations or uses vendor-specific versions of these mathematical algorithms where needed. This reduces the amount
    of architecture-specific software that an application team potentially needs to develop, thus further reducing their
    (modification cost)to achieve “best in class” performance.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://kokkos.org/api-kernels/
  dev_url: https://github.com/kokkos/kokkos-kernels

extra:
  recipe-maintainers:
    - BastianZim
    - vincentmr
    - rfiorella
